[project]
name = "circuitydatabase"
version = "10"
dependencies = [
    "typer",
]
requires-python = ">=3"
license = "MIT"
readme = "README.md"

[project.scripts]
circuity = "circuitydatabase.cli:app"
